### ISSUE TITLE
Add `include_isoform` parameter

### ISSUE THREAD

**Issue by godotgildor** [multimeric/Unipressed#26]
https://github.com/multimeric/Unipressed/blob/af5eea8c1cd6bd1b4739ab410b2acb8d03437d99/unipressed/dataset/core.py#L41-L47

The `Search` dataclass has a `include_isoform` member variable, but the `search` method of the `UniprotkbClient` class does not expose this as a parameter.

Can we add this as a parameter?

**Comment by multimeric** [comment]
Thanks for the issue. Yeah I'm not sure why I didn't include it as a parameter when it's part of the dataclass. Maybe I expected users to instantiate the dataclass directly? But that doesn't seem user-friendly so I'm happy to add it to `search()`.

**Comment by godotgildor** [comment]
Thanks for accepting the PR and thanks again for making the library.
